### ISSUE TITLE
How do you add a template?

### ISSUE THREAD

**Issue by Saorsa32** [Erallie/diarian#71]
I don't see were you can add a template in the settings. How do I add it?

**Comment by Saorsa32** [comment]
Are you talking about the plugin settings itself or in the obsidian core plugin templates?
________________________________

**Comment by Erallie** [comment]
@Saorsa32 I'm talking about both the obsidian core plugin Templates and the obsidian core plugin Daily notes.

**Comment by Saorsa32** [comment]
Ok. That helps! One last thing, does it connect to the Diarium app so that the daily notes would be in the app too? I want to be able to easily print out the pages like you can do in the app.  Thank you so much, for making this app and helping me out.
Laura
________________________________

**Comment by Erallie** [comment]
@Saorsa32 I don't exactly know what you mean by "connecting to the Diarium app". I have a feature where you can import entries from Diarium, but it's mainly to migrate your journal into Obsidian.

I feel like if you wanted to print out your journal, you could use [plugins that merge multiple notes together](https://obsidian.md/plugins?search=Merge%20notes) into a single note (aside from the ones that show up on search, I bookmarked this plugin called [Recursive Copy](https://obsidian.md/plugins?id=recursive-copy), but haven't tried it myself), and then plugins like [Pandoc](https://obsidian.md/plugins?id=obsidian-pandoc) to export it to a pdf or other file types, so you could print them using your own system. There may also be [plugins specifically for printing notes](https://obsidian.md/plugins?search=print) that you can use.

Outside of that though, I feel like a printing feature is not something that I would want to add to my plugin, but that you should use other plugins to do that.

If you're wanting to export your journal back to Diarium, I don't know if there's a way for me to store your journal in a format that Diarium accepts. I cannot look into the `.diary` files to see if I can copy it so you can import a journal back to Diarium like that, but maybe I can contact Diarium directly and ask if they can add support for importing a journal back from my Diarian plugin into Diarium. And work with them on a format in which I could export the daily notes so that they can import it back to Diarium. If it's a big thing you'd really like being implemented, I can ask them and get back to you!

**Comment by Saorsa32** [comment]
Thank you for your ideas. That really helps. Thank you for offering to look into more, but I think those options will help me do what I am looking for.
________________________________

**Comment by Erallie** [comment]
@Saorsa32 Okay then! If that's everything you need, I will close this issue now! If there's anything else you need, just comment again on this issue, and I will re-open it! Or create a new issue if it's unrelated!
